services: 
  web: 
    build:
     context: app
     target: builder
    stop_signal: SIGINT
    ports: 
      - '8000:8000'
    depends_on:
      - typesense
      - data-refresh
    volumes:
      - web_static:/app/static
  typesense:
    image: typesense/typesense:0.23.1
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=xyz --api-port=8100 --enable-cors"
    ports:
      - '8100:8100'
    volumes:
      - typesense-data:/data
  webproxy:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - web_static:/var/www-data
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - web
  data-refresh:
    build:
      context: discogs-update
      target: builder
    stop_signal: SIGINT
    depends_on:
      - typesense
  certbot:
    image: certbot/certbot
    depends_on:
      - webproxy
    volumes:
      - web_static:/var/www-data
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www-data --email library@wkcr.org --agree-tos --no-eff-email --force-renewal -d library.wkcr.org 

volumes:
  typesense-data:
    driver: local
  web_static:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
