# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Test and Deploy Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
    
      - name: Run test script
        working-directory: test
        run: |-
          ls -alF
          test.sh
        shell: bash
      
  deploy_to_gcloud:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    name: Deploy to Google Cloud
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'

      - name: Authenticate with Google
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1083452708352/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions@wkcr-library.iam.gserviceaccount.com'
      
      #- name: Check IAM
      #  run: |-
      #    gcloud auth login --no-launch-browser
      #    gcloud projects get-iam-policy library-site

      - name: SSH into Google Cloud and redeploy
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'library-site'
          zone: 'us-central1-c'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          user: library
          command: 'cd /home/library/wkcr-catalog; git pull; sudo docker compose up --build -d'
